server.port=8082
spring.application.name=sample-rest-service

spring.security.user.name=user
spring.security.user.password=123456

logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE

#  property used for testing   http://localhost:8082/actuator/health for databses specifically

management.endpoint.health.show-details=always

# Expose Actuator endpoints
management.endpoints.web.exposure.include=health,info,metrics,loggers,threaddump,heapdump,mappings,env,beans

#app.security.enabled=false // not working, need to explicitly exclude the security auto-configuration class